version: '2'
services:
  create_certs:
    container_name: create-certs
    build:
        context: create-certs/
    command: >
      bash -c '
        pwd
        ls -la
        chmod +x *.sh
        ./run.sh
        chown 1000:1000 ./certs
      '
    working_dir: /usr/share/elasticsearch/search-guard-ssl/pki-scripts
    volumes:
      - ./certs:/usr/share/elasticsearch/search-guard-ssl/pki-scripts/certs:rw