version: "2.2"

services:
  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/logs:/usr/share/logstash/logs:rw
      - ./certs:/usr/share/logstash/config/certs:ro
    ports:
      - $GELF_PORT:$GELF_PORT
      - $LOGSTASH_PORT:$LOGSTASH_PORT
    environment:
      ELASTICSEARCH_URL: $ELASTICSEARCH_URL
      LOGSTASH_USER: $LOGSTASH_USER
      LOGSTASH_PASSWORD: $LOGSTASH_PASSWORD
      LOGSTASH_PORT: $LOGSTASH_PORT
      GELF_PORT: $GELF_PORT
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    restart: on-failure
  logspout:
    build:
      context: extensions/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ROUTE_URIS: logstash+tcp://logstash:$LOGSTASH_PORT
      LOGSTASH_TAGS: $LOGSTASH_TAGS
    networks:
      - elk
    depends_on:
      - logstash
    restart: on-failure
networks:
  elk:
    driver: bridge
volumes:
  esdata_01:
    driver: local
  esdata_02:
    driver: local
