---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: ${ELASTICSEARCH_URL}
# SSL for outgoing requests from the Kibana Server (PEM formatted)
elasticsearch.ssl.verificationMode: none
#elasticsearch.ssl.ca: ./config/certs/ca/root-ca/root-ca.crt
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.ssl.certificateAuthorities: ./config/certs/ca/root-ca/root-ca.crt

server.ssl.enabled: true
server.ssl.key: ./config/certs/kibana/kibana.key.pem
server.ssl.certificate: ./config/certs/kibana/kibana.crt.pem
server.ssl.certificateAuthorities: ./config/certs/ca/root-ca/root-ca.crt
server.ssl.keyPassphrase: changeit