---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200
# SSL for outgoing requests from the Kibana Server (PEM formatted)
#server.ssl.enabled: true
#server.ssl.key: key.pem
#server.ssl.certificate: server.crt

#elasticsearch.username: "kibana"
#elasticsearch.password:  "<pwd>"
